version: '3.8'

services:
  # Jenkins сервис
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: keisenpai-jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - keisenpai-network
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    entrypoint:
      - /bin/tini
      - -- 
      - /usr/local/bin/jenkins.sh
    command: []


  # Java Services (Spring Boot)
  api-gateway:
    build: 
      context: ./services/api-gateway
    ports:
      - "8001:8080"
    networks:
      - keisenpai-network
    depends_on:
      - rabbitmq
      - auth-service

  auth-service:
    build: 
      context: ./services/auth-service
    ports:
      - "8002:8080"
    networks:
      - keisenpai-network
    depends_on:
      - users-db
      - rabbitmq
  admin-service:
    build: 
      context: ./services/admin-service
    ports:
      - "8001:8000"
    networks:
      - keisenpai-network
    depends_on:
      - rabbitmq
      - users-db

  user-service:
    build: 
      context: ./services/user-service
    ports:
      - "8002:8000"
    networks:
      - keisenpai-network
    depends_on:
      - users-db
      - rabbitmq

  payment-service:
    build: 
      context: ./services/payment-service
    ports:
      - "8104:8080"
    networks:
      - keisenpai-network
    depends_on:
      - payments-db
      - rabbitmq

  # Go Services (Gin)
  progress-service:
    build: 
      context: ./services/progress-service
    ports:
      - "8003:8000"
    networks:
      - keisenpai-network
    depends_on:
      - progress-db
      - rabbitmq

  
  courses-service:
    build: 
      context: ./services/courses-service
    ports:
      - "8101:8080"
    networks:
      - keisenpai-network
    depends_on:
      - courses-db
      - rabbitmq

  lessons-service:
    build: 
      context: ./services/lessons-service
    ports:
      - "8102:8080"
    networks:
      - keisenpai-network
    depends_on:
      - lessons-db
      - rabbitmq

  tests-service:
    build: 
      context: ./services/tests-service
    ports:
      - "8103:8080"
    networks:
      - keisenpai-network
    depends_on:
      - tests-db
      - rabbitmq


  # Python Services (FastAPI)
  achievement-service:
    build: 
      context: ./services/achievement-service
    ports:
      - "8201:8000"
    networks:
      - keisenpai-network
    depends_on:
      - achievements-db
      - rabbitmq

  material-service:
    build: 
      context: ./services/material-service
    ports:
      - "8202:8000"
    networks:
      - keisenpai-network
    depends_on:
      - materials-db
      - minio
      - video-storage
      - rabbitmq

  analytic-service:
    build: 
      context: ./services/analytic-service
    ports:
      - "8203:8000"
    networks:
      - keisenpai-network
    depends_on:
      - rabbitmq

  # Rust Services (Actix Web)
  notification-service:
    build: 
      context: ./services/notification-service
    ports:
      - "8301:8000"
    networks:
      - keisenpai-network
    depends_on:
      - rabbitmq

  search-service:
    build: 
      context: ./services/search-service
    ports:
      - "8302:8000"
    networks:
      - keisenpai-network
    depends_on:
      - rabbitmq

  # Инфраструктурные сервисы
  # Redis для кэширования и сессий
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - keisenpai-network

  # MinIO для объектного хранилища
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: keisenpai-storage
      MINIO_ROOT_PASSWORD: keisenpai2024-storage
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - keisenpai-network

  # Видеохранилище на основе nginx
  video-storage:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./video-storage:/usr/share/nginx/html/videos
    networks:
      - keisenpai-network

  # RabbitMQ для очередей сообщений
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: keisenpai
      RABBITMQ_DEFAULT_PASS: keisenpai2024-queue
    networks:
      - keisenpai-network

  # PostgreSQL базы данных для разных сервисов
  users-db:
    image: postgres:13
    environment:
      POSTGRES_DB: keisenpai_users
      POSTGRES_PASSWORD: keisenpai2024-users
    ports:
      - "5433:5432"
    volumes:
      - users-db-data:/var/lib/postgresql/data
    networks:
      - keisenpai-network

  progress-db:
    image: postgres:13
    environment:
      POSTGRES_DB: keisenpai_progress
      POSTGRES_PASSWORD: keisenpai2024-progress
    ports:
      - "5434:5432"
    volumes:
      - progress-db-data:/var/lib/postgresql/data
    networks:
      - keisenpai-network

  achievements-db:
    image: postgres:13
    environment:
      POSTGRES_DB: keisenpai_achievements
      POSTGRES_PASSWORD: keisenpai2024-achievements
    ports:
      - "5435:5432"
    volumes:
      - achievements-db-data:/var/lib/postgresql/data
    networks:
      - keisenpai-network

  payments-db:
    image: postgres:13
    environment:
      POSTGRES_DB: keisenpai_payments
      POSTGRES_PASSWORD: keisenpai2024-payments
    ports:
      - "5436:5432"
    volumes:
      - payments-db-data:/var/lib/postgresql/data
    networks:
      - keisenpai-network

  tests-db:
    image: postgres:13
    environment:
      POSTGRES_DB: keisenpai_tests
      POSTGRES_PASSWORD: keisenpai2024-tests
    ports:
      - "5437:5432"
    volumes:
      - tests-db-data:/var/lib/postgresql/data
    networks:
      - keisenpai-network

  lessons-db:
    image: postgres:13
    environment:
      POSTGRES_DB: keisenpai_lessons
      POSTGRES_PASSWORD: keisenpai2024-lessons
    ports:
      - "5438:5432"
    volumes:
      - lessons-db-data:/var/lib/postgresql/data
    networks:
      - keisenpai-network

  courses-db:
    image: postgres:13
    environment:
      POSTGRES_DB: keisenpai_courses
      POSTGRES_PASSWORD: keisenpai2024-courses
    ports:
      - "5439:5432"
    volumes:
      - courses-db-data:/var/lib/postgresql/data
    networks:
      - keisenpai-network

  materials-db:
    image: postgres:13
    environment:
      POSTGRES_DB: keisenpai_materials
      POSTGRES_PASSWORD: keisenpai2024-materials
    ports:
      - "5440:5432"
    volumes:
      - materials-db-data:/var/lib/postgresql/data
    networks:
      - keisenpai-network

networks:
  keisenpai-network:
    driver: bridge

volumes:
  #Jenkins
  jenkins_home:

  # БД тома
  users-db-data:
  progress-db-data:
  achievements-db-data:
  payments-db-data:
  tests-db-data:
  lessons-db-data:
  courses-db-data:
  materials-db-data:

  # MinIO том
  minio-data: